## HTTP Requests 
 GET http://127.0.0.1:5000/cvMaker/cvDesdeArchivo
 ?template=SimpleCustomA
#  ?template=SimpleA
#  ?template=BasicATS
#  ?template=FullATS
#  ?template=DoubleColumnA
 &lang=ESP
#  &lang=ENG
# &person=gb
 &person=fu
 &color=lightBlue
#  &color=darkRed
